version: "3.8"

services:
    web: &web
        build: .
        command: bash -c "service cron start &&
                          python manage.py makemigrations --noinput &&
                          python manage.py migrate &&
                          python manage.py collectstatic --noinput &&
                          python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./:/blog_app
        ports:
            - "8000:8000"
        depends_on:
            - db
            - rabbit
            - celery

    db:
        image: postgres:13
        env_file:
            - ./.env
        volumes:
            - ./pg_data:/var/lib/postgresql/data/
        ports:
            - "5050:5432"

    rabbit:
        image: rabbitmq
        ports:
            - '5672:5672'

    celery:
        <<: *web
        command: celery -A blog_app worker --loglevel=INFO
        ports: []
        depends_on:
            - db
            - rabbit


