# Generated by Django 3.2 on 2021-05-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210504_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_page_photo',
            field=models.ImageField(default='', upload_to='main_page_photos/%Y/%m/%d/', verbose_name='Фото на главной странице'),
        ),
    ]
