# Generated by Django 3.2 on 2021-05-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_subscribedata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribedata',
            options={'ordering': ('subscription_date',), 'verbose_name': 'данные подписчиков', 'verbose_name_plural': 'данные подписчиков'},
        ),
    ]
