# Generated by Django 3.2 on 2021-05-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_subscribedata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subscription_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
            ],
            options={
                'verbose_name': 'данные подписчиков',
                'verbose_name_plural': 'данные подписчиков',
                'ordering': ('subscription_date',),
            },
        ),
        migrations.DeleteModel(
            name='SubscribeData',
        ),
    ]
