# Generated by Django 3.2 on 2021-05-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210524_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='subscriber_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
