# Generated by Django 3.2 on 2021-05-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_subscribe_subscriber_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='subscriber_email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Email'),
        ),
    ]
